
# 该配置需要将服务引入seata服务器进行运行，不然无法运行
service {
  #transaction service group mapping
  vgroupMapping.default_tx_group = "default" #事务分组
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "172.18.0.2:8090" #此指定了seata服务器的地址，此为TC的端口，7091为web端口
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}