
# 该配置需要将服务引入seata服务器进行运行，不然无法运行
service {
  # 必须和你的tx-service-group一致：my_test_tx_group -> default集群
  vgroupMapping.my_test_tx_group = "default"
  # Seata Server地址（容器IP+8090端口）
  default.grouplist = "172.19.0.2:8090"
  # 关闭降级
  enableDegrade = false
  # 不关闭全局事务
  disableGlobalTransaction = false
}